### ISSUE TITLE
Split from PizzaFactory/che-theia.

### ISSUE THREAD

**Issue by monaka** [opentestmodeling/che-theia#1]
- [x] Build on Azure DevOps Pipelines. (#2)
- [x] Push to Docker Hub. (#2)
- [x] Open the issue ticket to make fix the plugin registry on PizzaFactory/Camino. (PizzaFactory/che-plugin-registry#26)

**Comment by monaka** [comment]
I close it as all tasks are done.
